#!/bin/bash
#
# sync-ai-rules.sh
# Syncs shared rules from claude/.ai-rules/ plus project-specific rules
# to .cursor/rules/, .claude/rules/, and Codex AGENTS.md in each project.
#
# Project-specific rules override shared rules when filenames conflict.
#
# Run from claude directory: ./.ai-rules/sync-ai-rules.sh
#

set -e

# Get directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JORDAN_OS_DIR="$(dirname "$SCRIPT_DIR")"
SHARED_RULES_DIR="$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "🔄 Syncing AI rules across claude projects..."
echo ""

# Codex AGENTS block markers
CODEX_BLOCK_START="<!-- BEGIN: AI RULES SYNC (generated) -->"
CODEX_BLOCK_END="<!-- END: AI RULES SYNC (generated) -->"

# Discover projects
discover_projects() {
    local projects=()
    for dir in "$JORDAN_OS_DIR"/*/; do
        [ -d "$dir" ] || continue
        local name=$(basename "$dir")
        # Skip hidden directories and the .ai-rules directory itself
        [[ "$name" == .* ]] && continue
        # Check if it's a project workspace
        if [ -f "$dir/CLAUDE.md" ] || [ -d "$dir/.git" ] || [ -f "$dir/.claude/settings.local.json" ] || [ -d "$dir/.ai-rules" ]; then
            projects+=("$name")
        fi
    done
    echo "${projects[@]}"
}

# Function to add alwaysApply: true to frontmatter
add_always_apply() {
    local input_file="$1"
    local output_file="$2"
    local value="${3:-true}"

    if head -1 "$input_file" | grep -q "^---$"; then
        if grep -q "alwaysApply:" "$input_file"; then
            cp "$input_file" "$output_file"
        else
            awk -v val="$value" '
                NR==1 { print; next }
                /^---$/ && !added { print "alwaysApply: " val; added=1 }
                { print }
            ' "$input_file" > "$output_file"
        fi
    else
        {
            echo "---"
            echo "alwaysApply: $value"
            echo "---"
            echo ""
            cat "$input_file"
        } > "$output_file"
    fi
}

# Remove YAML frontmatter from markdown files when embedding in AGENTS.md
strip_frontmatter() {
    local input_file="$1"

    if head -1 "$input_file" | grep -q "^---$"; then
        awk '
            NR==1 && $0=="---" { in_frontmatter=1; next }
            in_frontmatter && $0=="---" { in_frontmatter=0; next }
            in_frontmatter { next }
            { print }
        ' "$input_file"
    else
        cat "$input_file"
    fi
}

append_codex_rule() {
    local file="$1"
    local source_path="$2"
    local output_file="$3"
    local rule_name
    rule_name=$(basename "$file" .md)

    {
        echo "#### \`$rule_name\`"
        echo "_Source: \`$source_path\`_"
        echo ""
        strip_frontmatter "$file"
        echo ""
    } >> "$output_file"
}

build_codex_block() {
    local project_name="$1"
    local project_rules_dir="$2"
    local output_file="$3"

    CODEX_RULE_COUNT=0
    local global_written=0
    local conditional_written=0

    {
        echo "$CODEX_BLOCK_START"
        echo "## AI Rules (Synced)"
        echo ""
        echo "_Generated by \`$SCRIPT_DIR/sync-ai-rules.sh\` on $(date +%Y-%m-%d)._"
        echo "_Edit source rules in \`.ai-rules/\`; do not edit this block directly._"
        echo ""
        echo "### Global Rules (Always Apply)"
        echo ""
    } > "$output_file"

    # Shared global rules
    if [ -d "$SHARED_RULES_DIR/global" ]; then
        for file in "$SHARED_RULES_DIR/global/"*.md; do
            [ -f "$file" ] || continue
            local basename
            basename=$(basename "$file" .md)
            # Skip if project overrides this rule
            if [ -f "$project_rules_dir/global/$basename.md" ]; then
                continue
            fi
            append_codex_rule "$file" ".ai-rules/global/$basename.md" "$output_file"
            global_written=1
            CODEX_RULE_COUNT=$((CODEX_RULE_COUNT + 1))
        done
    fi

    # Project global rules
    if [ -d "$project_rules_dir/global" ]; then
        for file in "$project_rules_dir/global/"*.md; do
            [ -f "$file" ] || continue
            local basename
            basename=$(basename "$file" .md)
            append_codex_rule "$file" "$project_name/.ai-rules/global/$basename.md" "$output_file"
            global_written=1
            CODEX_RULE_COUNT=$((CODEX_RULE_COUNT + 1))
        done
    fi

    if [ "$global_written" -eq 0 ]; then
        echo "- None" >> "$output_file"
        echo "" >> "$output_file"
    fi

    {
        echo "### Conditional Rules (Apply When Relevant)"
        echo ""
    } >> "$output_file"

    # Shared conditional rules
    if [ -d "$SHARED_RULES_DIR/conditional" ]; then
        for file in "$SHARED_RULES_DIR/conditional/"*.md; do
            [ -f "$file" ] || continue
            local basename
            basename=$(basename "$file" .md)
            if [ -f "$project_rules_dir/conditional/$basename.md" ]; then
                continue
            fi
            append_codex_rule "$file" ".ai-rules/conditional/$basename.md" "$output_file"
            conditional_written=1
            CODEX_RULE_COUNT=$((CODEX_RULE_COUNT + 1))
        done
    fi

    # Project conditional rules
    if [ -d "$project_rules_dir/conditional" ]; then
        for file in "$project_rules_dir/conditional/"*.md; do
            [ -f "$file" ] || continue
            local basename
            basename=$(basename "$file" .md)
            append_codex_rule "$file" "$project_name/.ai-rules/conditional/$basename.md" "$output_file"
            conditional_written=1
            CODEX_RULE_COUNT=$((CODEX_RULE_COUNT + 1))
        done
    fi

    if [ "$conditional_written" -eq 0 ]; then
        echo "- None" >> "$output_file"
        echo "" >> "$output_file"
    fi

    {
        echo "$CODEX_BLOCK_END"
        echo ""
    } >> "$output_file"
}

upsert_codex_agents() {
    local agents_file="$1"
    local generated_block_file="$2"
    local temp_file
    temp_file=$(mktemp)

    if [ -f "$agents_file" ]; then
        if grep -qF "$CODEX_BLOCK_START" "$agents_file" && grep -qF "$CODEX_BLOCK_END" "$agents_file"; then
            awk -v start="$CODEX_BLOCK_START" -v end="$CODEX_BLOCK_END" -v block_file="$generated_block_file" '
                BEGIN {
                    while ((getline line < block_file) > 0) {
                        block = block line ORS
                    }
                    close(block_file)
                    replaced = 0
                    skipping = 0
                }
                $0 == start {
                    printf "%s", block
                    skipping = 1
                    replaced = 1
                    next
                }
                $0 == end {
                    skipping = 0
                    next
                }
                skipping != 1 { print }
                END {
                    if (replaced == 0) {
                        if (NR > 0) print ""
                        printf "%s", block
                    }
                }
            ' "$agents_file" > "$temp_file"
        else
            {
                cat "$agents_file"
                echo ""
                cat "$generated_block_file"
            } > "$temp_file"
        fi
    else
        cat "$generated_block_file" > "$temp_file"
    fi

    mv "$temp_file" "$agents_file"
}

# Sync rules to a single project
sync_project() {
    local project_name="$1"
    local project_dir="$JORDAN_OS_DIR/$project_name"
    local project_rules_dir="$project_dir/.ai-rules"
    local cursor_out="$project_dir/.cursor/rules"
    local claude_out="$project_dir/.claude/rules"
    local claude_skills_out="$project_dir/.claude/skills"
    local codex_agents="$project_dir/AGENTS.md"
    local codex_block_tmp
    codex_block_tmp=$(mktemp)

    echo -e "${BLUE}📦 $project_name${NC}"

    # Create output directories
    mkdir -p "$cursor_out" "$claude_out" "$claude_skills_out"

    # Track counts
    local global_count=0
    local conditional_count=0
    local skill_count=0
    local codex_count=0

    # --- GLOBAL RULES ---
    # First: shared global rules
    if [ -d "$SHARED_RULES_DIR/global" ]; then
        for file in "$SHARED_RULES_DIR/global/"*.md; do
            [ -f "$file" ] || continue
            local basename=$(basename "$file" .md)
            # Check if project has override
            if [ -f "$project_rules_dir/global/$basename.md" ]; then
                continue  # Skip, project will override
            fi
            add_always_apply "$file" "$cursor_out/${basename}.mdc"
            global_count=$((global_count + 1))
        done
    fi

    # Then: project-specific global rules (override shared)
    if [ -d "$project_rules_dir/global" ]; then
        for file in "$project_rules_dir/global/"*.md; do
            [ -f "$file" ] || continue
            local basename=$(basename "$file" .md)
            add_always_apply "$file" "$cursor_out/${basename}.mdc"
            global_count=$((global_count + 1))
        done
    fi

    # --- CONDITIONAL RULES ---
    # First: shared conditional rules
    if [ -d "$SHARED_RULES_DIR/conditional" ]; then
        for file in "$SHARED_RULES_DIR/conditional/"*.md; do
            [ -f "$file" ] || continue
            local basename=$(basename "$file" .md)
            if [ -f "$project_rules_dir/conditional/$basename.md" ]; then
                continue  # Skip, project will override
            fi
            add_always_apply "$file" "$cursor_out/${basename}.mdc" "false"
            cp "$file" "$claude_out/${basename}.md"
            conditional_count=$((conditional_count + 1))
        done
    fi

    # Then: project-specific conditional rules
    if [ -d "$project_rules_dir/conditional" ]; then
        for file in "$project_rules_dir/conditional/"*.md; do
            [ -f "$file" ] || continue
            local basename=$(basename "$file" .md)
            add_always_apply "$file" "$cursor_out/${basename}.mdc" "false"
            cp "$file" "$claude_out/${basename}.md"
            conditional_count=$((conditional_count + 1))
        done
    fi

    # --- SKILLS (Claude Code only) ---
    # First: shared skills
    if [ -d "$SHARED_RULES_DIR/skills" ]; then
        for skill_dir in "$SHARED_RULES_DIR/skills/"*/; do
            [ -d "$skill_dir" ] || continue
            local skill_name=$(basename "$skill_dir")
            # Check if project has override
            if [ -d "$project_rules_dir/skills/$skill_name" ]; then
                continue  # Skip, project will override
            fi
            mkdir -p "$claude_skills_out/$skill_name"
            for file in "$skill_dir"*; do
                [ -f "$file" ] || continue
                cp "$file" "$claude_skills_out/$skill_name/"
            done
            skill_count=$((skill_count + 1))
        done
    fi

    # Then: project-specific skills
    if [ -d "$project_rules_dir/skills" ]; then
        for skill_dir in "$project_rules_dir/skills/"*/; do
            [ -d "$skill_dir" ] || continue
            local skill_name=$(basename "$skill_dir")
            mkdir -p "$claude_skills_out/$skill_name"
            for file in "$skill_dir"*; do
                [ -f "$file" ] || continue
                cp "$file" "$claude_skills_out/$skill_name/"
            done
            skill_count=$((skill_count + 1))
        done
    fi

    # --- CODEX AGENTS ---
    build_codex_block "$project_name" "$project_rules_dir" "$codex_block_tmp"
    codex_count="$CODEX_RULE_COUNT"
    upsert_codex_agents "$codex_agents" "$codex_block_tmp"
    rm -f "$codex_block_tmp"

    echo "   ✓ Global: $global_count | Conditional: $conditional_count | Skills: $skill_count | Codex rules: $codex_count"
}

# Main
echo "🔍 Discovering projects..."
projects=($(discover_projects))
echo "   Found: ${projects[*]}"
echo ""

for project in "${projects[@]}"; do
    sync_project "$project"
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✓ Sync complete!${NC}"
echo ""
echo "Shared rules: $SHARED_RULES_DIR"
echo "Projects synced: ${#projects[@]}"
echo ""
echo -e "${YELLOW}Remember: Edit shared rules in claude/.ai-rules/${NC}"
echo -e "${YELLOW}          Edit project rules in {project}/.ai-rules/${NC}"
